server:
  port: 8080
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:microservice}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:0000}
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
  sql:
    init:
      mode: never
      platform: mysql
  profiles:
    active:
      - "qa"
logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"



build:
  version: "3.0"

accounts:
  message: "Welcome to EazyBank accounts related local APIs "
  contactDetails:
    name: "John Doe - Developer"
    email: "john@eazybank.com"
    linkedIn: "jmenete@linkedIn.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
