server:
  port: 9000
spring:
  application:
    name: cards
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:microservice}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:0000}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
  sql:
    init:
      mode: never
      platform: mysql

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}



