server:
  port: 9000
spring:
  application:
    name: accounts
  datasource:
    url: jdbc:mysql://${DATABASE_HOST:localhost}:${DATABASE_PORT:3306}/${DATABASE_NAME:microservice}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:0000}
  jpa:
    show-sql: ${JPA_SHOW_SQL:true}
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: ${HIBERNATE_FORMAT_SQL:true}
  sql:
    init:
      mode: never
      platform: mysql

logging:
  pattern:
    console: ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
  config:
    import:
      - "application_qa.yml"
      - "application_prod.yml"
  profiles:
    active:
      - "qa"

build:
  version: "3.0"

cards:
  message: "Welcome to EazyBank cards related local APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@eazybank.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932
